# Generated by Django 4.2.9 on 2024-02-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_item_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Items'},
        ),
    ]
